### ISSUE TITLE
Widgets don't work on RR

### ISSUE THREAD

**Issue by nebrassy** [xiaomi-sdm660/android_build_bug-tracker#10]
**Device:** Mi A2
**ROM Version :** RR-P-v7.0.0-20190120-jasmine-Official
**Kernel version:** 4.4.171-perf+
**Android version:** 9

**Description**
Widgets on RR don't work, keep getting "error loading widget" on all launchers

**Symptoms**
No widgets can load except shortcuts and a few others like media controls

**How to reproduce**
Add clock widget to the homescreen

**Comment by rcstar6696** [comment]
Rom issue and not device related
