### ISSUE TITLE
Media Sound Settings

### ISSUE THREAD

**Issue by ErvinJohnEstrera** [xiaomi-sdm660/android_build_bug-tracker#11]
**Device:**  MI A2
**ROM Version :** Havoc 2.2
**Kernel version:** 4.4.174
**Android version:**  Android 9

**Description**
Media / Sound settings resetting to default values after every reboot.

**Symptoms**
After a reboot, all sounds settings is going back to its default values.
Tested on Many Jasmine_Sprout Roms, same problem.

**How to reproduce**
Change Media Settings values, notification volume, ring volume and etc, and reboot, it will go back to its factory values.

**Comment by rcstar6696** [comment]
i can't reproduce it sorry do you use any sound mod and since what build you face it?

**Comment by ErvinJohnEstrera** [comment]
No, I  don't use any sound mods. Since 2.1. I even unchecked the link notification and ring volume, and once I reboot, it is checked again. The values I set for my preferred volume for my device is resetting every time I reboot which is really annoying. And in the latest Havoc 2/16, it's still present.

**Comment by rcstar6696** [comment]
now i can reproduce i will ping lead developers of havoc thats rom issue if you link volume it works

**Comment by ErvinJohnEstrera** [comment]
Thanks Max, you are awesome. We are lucky we got you in 660 dev.
