### ISSUE TITLE
SLOW CHARGING THAN STOCK ROM

### ISSUE THREAD

**Issue by ErvinJohnEstrera** [xiaomi-sdm660/android_build_bug-tracker#12]
**Device:** MI A2
**ROM Version :** Havoc 2.2
**Kernel version:** 4.4.174
**Android version:** Android Pie

**Description**
Slow charging, quick charge 3 and normal charger. 
In stock I reach 2K, but in custom ROMs, I only reach 1500 highest, and quick charge 3 only 2K instead instead of 2900.
Tested all ROMs for MI A2 but the same, must be a device tree error I think?

**Symptoms**
Using stock charger and quick charger slower than stock AndroidOne ROM.

**How to reproduce**
Compare charging of Stock ROM vs Custom ROM, I am in havoc but it is the same in all ROM.

**Comment by rcstar6696** [comment]
should be fixed

**Comment by eun0115** [comment]
same issues with my realme 5, it charges from 500 to 900a only

**Comment by ctwoon** [comment]
@gianestacio realme has nothing to do with our repos
