### ISSUE TITLE
Android Q Clock incorrect

### ISSUE THREAD

**Issue by Hamsururu92** [xiaomi-sdm660/android_build_bug-tracker#13]
**Device: Xiaomi Mi A2
**ROM Version : Havoc 2.5 19-05-2019
**Kernel version: 4.4.180 Xiaomi
**Android version: Android 9

**Description**
In Portuguese Language, the clock Android Q on locked screen have one hour more than clock on status bar. It only happens on Portuguese Language, in English works perfectly

**How to reproduce**
Change Language to Portuy
![Screenshot_20190520-142608](https://user-images.githubusercontent.com/50835050/58026560-a769d400-7b0e-11e9-9e24-03268fbb8217.png)
![Screenshot_Lawnchair_20190520-142931](https://user-images.githubusercontent.com/50835050/58026562-a769d400-7b0e-11e9-9a1d-6d38179d8471.png)
![Screenshot_Lawnchair_20190520-142600](https://user-images.githubusercontent.com/50835050/58026563-a8026a80-7b0e-11e9-8952-4b621318069b.png)
![Screenshot_20190520-142953](https://user-images.githubusercontent.com/50835050/58026564-a8026a80-7b0e-11e9-8ccc-adace87bdf15.png)

**Comment by ctwoon** [comment]
Not device related
