### ISSUE TITLE
[Clover] Randomly hangs on boot or in some apps with the last august update

### ISSUE THREAD

**Issue by ghost** [xiaomi-sdm660/android_build_bug-tracker#14]
**Device:**  Mi Pad 4 Plus
**ROM Version :** Havoc 2.8 (19-22-26 August)
**Kernel version:**  Havoc kernel
**Android version:** Android 9

**Description**
Some google apps, services, operations hangs and not work.

**How to reproduce**
The problema appears after a clean or a dirty flash.
With the dirty flash gmail/play store hangs randomly, with a clean flash the tablet hangs on the first run on "Checking for updates..." 
Switching connection from wifi to (for example) my mobile, works but reconnecting to wifi the problem randomly reappear.

I was thinking that the problem was related to google apps but the 27 august's gapps works with the 2.7 havoc version and not with any of the 3 2.8.

**Comment by PythonLimited** [comment]
I actually had the same issue on my LOS builds, a clean wipe and a new vendor image fixed it for me...

**Comment by rcstar6696** [comment]
Hey i already tired to reproduce it on mi pad4 plus with open gapps arm64 mini from 23th august and all went fine. 

Sometimes device can hang at the searching for updates but then go back to wifi connect step tap on your wifi you want to connect and try again. After that it always worked for me


Btw the issue title is wrong ....

**Comment by ghost** [comment]
Your solution doesn't work, going back and reconnect to WiFi (same or other no differences) always hangs. The problem is related to the august update, all the roms i have tried (pixel, havoc) hangs with different gapps version and also with mindthegapps.
