### ISSUE TITLE
Black screen automatic hot restart at night

### ISSUE THREAD

**Issue by N2githa** [xiaomi-sdm660/android_build_bug-tracker#15]
Device:mi pad4
ROM Version :havoc os 2.8 (20190826)
Kernel version:4.4.190
Android version:Android9.0
An automatic hot restart occurs after the screen is turned off at night. Currently, there is no way to find duplicate problems. There are two logs. The hot restart occurs before 09-01 00:34~00:37, and the other log comes from data/data/anr. The fault occurs. When data/data/anr appears trace_00
log:https://drive.google.com/open?id=1yCjNR4oqJA8JwbPduIf9ZJrRFBLTBRJ3

**Comment by N2githa** [comment]
![IMG_20190901_095042](https://user-images.githubusercontent.com/54716755/64070820-0ad2d880-cc9e-11e9-8f92-8310b6b10a50.jpg)

**Comment by rcstar6696** [comment]
Does it happen regulary ? So i mean every day? The only thing your log shows is a small issue with mtp but nothing which would cause a reboot. Your are the only one who faces it ? Did you clean install v2.8?

**Comment by N2githa** [comment]
> Does it happen regulary ? So i mean every day? The only thing your log shows is a small issue with mtp but nothing which would cause a reboot. Your are the only one who faces it ? Did you clean install v2.8?

I did not format the data partition and only cleared the system partition. This automatic hot restart event has occurred twice.

**Comment by rcstar6696** [comment]
Please do a proper clean install. No need to wipe internal storage but at least data wipe needed.

**Comment by N2githa** [comment]
> Please do a proper clean install. No need to wipe internal storage but at least data wipe needed.

Restart is a hot restart, just like shutdown-hot restart, the symptom is a sudden black screen, and then reload the desktop lock screen, without animation.
Okay, I'll erase the data. Can I restore the app with a Titanium backup later?

**Comment by rcstar6696** [comment]
Yes sure thats fine

**Comment by N2githa** [comment]
> Yes sure thats fine

Thank you. When will the Havoc OS September patch be updated? I want to format the data in the next update, and then restore the app with a titanium backup.
