### ISSUE TITLE
Banking App detecting root on unrooted system

### ISSUE THREAD

**Issue by ricku44** [xiaomi-sdm660/android_build_bug-tracker#16]
**Device:** MiA2
**ROM Version :**  Latest
**Kernel version:** Latest
**Android version:** 9

**Description**
Write the issue description here.
After update, Banking App detecting root on unrooted system.

**Symptoms**
Write the symptoms here.

**How to reproduce**
Write how to reproduce here.

**Comment by rcstar6696** [comment]
Hey just as an info your bug report is incomplete and will get ignored
We don't know what rom you use. We don't know the kernel. You not posted a way to reproduce. 
We not even know anything excpt you have an a2 with borken bank app. 

Anyway i would recommand to flash magisk and enable magisk hide for the bank app you use

**Comment by ricku44** [comment]
Forgive my rudeness & laziness..

Please find the information below:
You can directly contact me if you want further details.
Thanks in advance.


Device: MiA2
ROM Version : 2.8
Build Date: 26-08-2019
Kernel version: 4.4.190
Android version: 9

Description
After update, Banking App detecting root on unrooted system. Tried after rooting & magisk hide, getting message: unable to reach bank servers.

App: Hdfc Mobile Banking,
Allahabad Bank empower

How to reproduce
Download Hdfc Bank app, open it you will get root detection error. Use magisk hide & hide magisk manager package name, open app click on UPI Registration, you will get error: unable to reach bank servers.

**Comment by ricku44** [comment]
Please do inform me when the issue is resolved until then gonna use Ver. 2.7

**Comment by PythonLimited** [comment]
is the issue still present in the newer builds?

**Comment by ricku44** [comment]
Yes

**Comment by ericcostes** [comment]
Hi,
with this bug doest it mean we cannot use google pay on unroot systems at the moment ?

**Comment by rcstar6696** [comment]
Only with magisk hide possible. But we can't do much about it as we pass all safetynet tests without problems. With magisk google pay works

**Comment by ericcostes** [comment]
ok thanks :)
