### ISSUE TITLE
After a clean installation, the system has a black screen hot restart again.

### ISSUE THREAD

**Issue by N2githa** [xiaomi-sdm660/android_build_bug-tracker#17]
Device:mi pad4
ROM Version :havoc os 2.8 (20190826)
Kernel version:4.4.190
Android version:Android9.0
Log, time: 09-11 09:05:00-09:07. The log contains both trace_02 and trace_02 from data/anr.
log:https://drive.google.com/open?id=1jvHnhHL4GJdlmkMx4iWapNJ36fx2yW_s

**Comment by N2githa** [comment]
09-11 09:06:00.707 E/AndroidRuntime(12888): *** FATAL EXCEPTION IN SYSTEM PROCESS: FinalizerWatchdogDaemon
09-11 09:06:00.707 E/AndroidRuntime(12888): java.util.concurrent.TimeoutException: android.media.Ringtone.finalize() timed out after 10 seconds
09-11 09:06:00.707 E/AndroidRuntime(12888): 	at android.media.MediaPlayer._release(Native Method)
09-11 09:06:00.707 E/AndroidRuntime(12888): 	at android.media.MediaPlayer.release(MediaPlayer.java:2162)
09-11 09:06:00.707 E/AndroidRuntime(12888): 	at android.media.Ringtone.finalize(Ringtone.java:484)
09-11 09:06:00.707 E/AndroidRuntime(12888): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
09-11 09:06:00.707 E/AndroidRuntime(12888): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
09-11 09:06:00.707 E/AndroidRuntime(12888): 	at java.lang.Daemons$Daemon.run(Daemons.java:103)
09-11 09:06:00.707 E/AndroidRuntime(12888): 	at java.lang.Thread.run(Thread.java:764)
09-11 09:06:00.709 I/am_crash(12888): [12888,0,system_server,-1,java.util.concurrent.TimeoutException,android.media.Ringtone.finalize() timed out after 10 seconds,MediaPlayer.java,-2]
09-11 09:06:00.999 I/init    (    0): Service 'zygote' (pid 12684) received signal 9
09-11 09:06:00.999 I/init    (    0): Sending signal 9 to service 'zygote' (pid 12684) process group...
09-11 09:06:01.021 I/libprocessgroup(    0): Successfully killed process cgroup uid 0 pid 12684 in 21ms
09-11 09:06:01.028 I/init    (    0): Command 'write /sys/power/state on' action=onrestart (<Service 'zygote' onrestart>:2) took 1ms and failed: Unable to write to file '/sys/power/state': Unable to write file contents: Invalid argument
09-11 09:06:01.029 I/init    (    0): Sending signal 9 to service 'audioserver' (pid 12686) process group...
09-11 09:06:01.069 D/tas2557s 6-004c(    0): tas2557_mute
09-11 09:06:01.069 I/tas2557s 6-004c(    0): Enable: 0
09-11 09:06:01.072 I/libprocessgroup(    0): Successfully killed process cgroup uid 1041 pid 12686 in 43ms
09-11 09:06:01.074 I/init    (    0): Sending signal 9 to service 'cameraserver' (pid 12687) process group...
09-11 09:06:01.079 I/libprocessgroup(    0): Successfully killed process cgroup uid 1047 pid 12687 in 5ms
09-11 09:06:01.081 I/init    (    0): Sending signal 9 to service 'media' (pid 12688) process group...

**Comment by PythonLimited** [comment]
Havoc has been dropped since Q came out.
Also i assume this has been resolved as its over a month now since this is open.
Maybe update your vendor if the problem still persists.
