### ISSUE TITLE
[clover] Audio static/hissing noise with headphones

### ISSUE THREAD

**Issue by ddmoore95** [xiaomi-sdm660/android_build_bug-tracker#18]
**Device: clover** 
**ROM Version : 2.8** 
**Kernel version: 4.4.190** 
**Android version: 9** 

**Description**
When playing videos and listening to music, there is audio distortion and static. It is especially noticeable during speaking parts of videos.

The ability to adjust audio gain in a previous version helped to fix the issue, but now this option is no longer available in the settings menu.

**Symptoms**
Audio hissing
Audio distortion, especially at low volume levels

**How to reproduce**
Listen to videos with talking with in ear headphones in.

**Comment by PythonLimited** [comment]
Same thing happens for me too but with the Speakers.
I cant confirm the distortion but the hissing is present in all builds i had so far.

**Comment by rcstar6696** [comment]
This should be fixed in 10
