### ISSUE TITLE
Video recording problem

### ISSUE THREAD

**Issue by youms** [xiaomi-sdm660/android_build_bug-tracker#19]
**Device: jasmine_sprout (Mi A2)** 
**ROM Version: 2.8** 
**Kernel version: 4.4.190** 
**Android version: 9.0** 

**Description**
Video recording low and distorted sound volume

**Symptoms**
Videos recorded have poor sound, noticeable when recording a speech

**How to reproduce**
Record a video with any camera app

**Comment by rcstar6696** [comment]
pie is no longer maintained 
please test on android 10 builds
