### ISSUE TITLE
Sound is too loud

### ISSUE THREAD

**Issue by tom-rade** [xiaomi-sdm660/android_build_bug-tracker#2]
**Device:** Mi A2
**ROM Version :** crDroid 20181228
**Kernel version:** 4.4.169-hex
**Android version:** 9

The sound (both speaker and headphones) is way too loud. But especially the phone speaker.

Even at minimal volume, my hear bleed when I hear the alarm or when I'm phoning with people.

**Comment by rcstar6696** [comment]
Should be better in next build
