### ISSUE TITLE
5ghz wifi networks absent...

### ISSUE THREAD

**Issue by bobtrawler** [xiaomi-sdm660/android_build_bug-tracker#20]
**mipad4:** 
**latest unofficial lineage :** 
**Kernel version:** 
**10:** 

**Description**
No 5g wifi visible

**Symptoms**
Write the symptoms here.

**How to reproduce**
Write how to reproduce here.

**Comment by rcstar6696** [comment]
Working fine here 
https://imgur.com/hz4tN2F

So issue on your end
