### ISSUE TITLE
Status bar issues

### ISSUE THREAD

**Issue by mobihen** [xiaomi-sdm660/android_build_bug-tracker#24]
**Device: Mi Pad 4 Plus** 
**ROM Version : 17 - linage_clover-userdebug 10 QPA1A.191005.007** 
**Kernel version:  4.4.198-Xiaomi_SDM660-LA.UM.8.2.r1-04800+
**Android version: 10 

**Description**
Percentage, Quick Pull down, Battery status style not working.

**How to reproduce**
Settings -> System -> Status bar

**Comment by rcstar6696** [comment]
Rom Source issue not device releated
