### ISSUE TITLE
twrp is not booting

### ISSUE THREAD

**Issue by nhmanas** [xiaomi-sdm660/android_build_bug-tracker#3]
mi a2
10.0.2 official
patched 10.0.2 kernel rooted with magisk

I can't boot into twrp. I tried several twrp builds, one is not booting others only give black screen
adb devices output says my devices is in recovery state but there is no twrp on the screen

**Comment by rcstar6696** [comment]
That issue tracker is for custom roms only 
Not for mi a2 official builds. No one of us builds twrp. Sorry

**Comment by nhmanas** [comment]
I didn't know that, sorry about confusion.
