### ISSUE TITLE
[jasmine_sprout] No signature spoofing

### ISSUE THREAD

**Issue by azakosath** [xiaomi-sdm660/android_build_bug-tracker#4]
**Device:** jasmine_sprout
**ROM Version :** crDroidAndroid-9.0-20181228-jasmine-v5.0 or Havoc-OS-v2.0-20181231-jasmine-Official
**Kernel version:** stock
**Android version:** 9

**Description**
Signature spoofing does not work on crDroid or HavocOS, but works correctly on AospExtended (AospExtended-v6.1-jasmine-20190103-1214-UNOFFICIAL). 

**Symptoms**
When signature spoofing permission is enabled in Havoc or crDroid settings and granted to apps requested it, those apps can not spoof package signature as they were supposed to do.

**How to reproduce**
Install microG (use NanoDroid) or Signature Spoofing Checker from F-Droid

**Comment by azakosath** [comment]
The problem persists in the new builds (11/01 for crDroid and 12/01 for Havoc), even though the changelong says otherwise. The workaround is to flash the Nanodroid patcher.
I guess the problem is in the upstream sources where both ROMs cherry-pick the signature patch, should I leave this issue open or should I close it, @rcstar6696?

**Comment by rcstar6696** [comment]
Not a device issue
