### ISSUE TITLE
Preferred network type

### ISSUE THREAD

**Issue by alextrofo** [xiaomi-sdm660/android_build_bug-tracker#6]
**Device: Mi A2
**ROM Version : Havoc 31/12/2018
**Kernel version: Stock
**Android version: 9.0

**Description**
After a clean install you need to switch manually to LTE/WCDMA because is set by default to WCDMA 

**How to reproduce**
Clean install / factory reset

**Comment by rcstar6696** [comment]
Thats an issue in havoc source not device related issue
