### ISSUE TITLE
USB detection after a clean install

### ISSUE THREAD

**Issue by alextrofo** [xiaomi-sdm660/android_build_bug-tracker#7]
**Device: Mi A2
**ROM Version : Havoc 31/12/2018
**Kernel version: Hex kernel build 1 January 
**Android version: 9.0

**Description**
After a clean install or factory reset, I need to restart my phone because it can't detect my laptop also I tried to enable/disable USB debug. 

**How to reproduce**
Clean install/factory reset and before first boot install Hex kernel

**Comment by rcstar6696** [comment]
Hex is not supported
