### ISSUE TITLE
Cannot add a new user from status bar menu

### ISSUE THREAD

**Issue by IAmJulianAcosta** [xiaomi-sdm660/android_build_bug-tracker#9]
**Device:** Mi Pad
**ROM Version :** 20190112 / 2.1
**Kernel version:** 4.5.169-perf
**Android version:** 9

**Description**
Cannot add a new user from status bar menu

**Symptoms**
First time tablet goes to lock screen, second time it freezes

**How to reproduce**
Open status bar menu
Click on user icon
Click on add user
![image](https://user-images.githubusercontent.com/1844640/51413686-ba0ed500-1b3d-11e9-8c6a-752e5542e5f7.png)

Note that it works fine when going to system app

Attached, full logs:
[log 1.txt](https://github.com/xiaomi-sdm660/android_build_bug-tracker/files/2774579/log.1.txt)
[log 2.txt](https://github.com/xiaomi-sdm660/android_build_bug-tracker/files/2774581/log.2.txt)
[log 3.txt](https://github.com/xiaomi-sdm660/android_build_bug-tracker/files/2774580/log.3.txt)

I think that the most relevant part of the logs is:

```
01-18 13:52:43.380  3085  3085 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.systemui.statusbar.phone.SystemUIDialog$DismissReceiver.register()' on a null object reference
01-18 13:52:43.380  3085  3085 E AndroidRuntime:        at com.android.systemui.statusbar.phone.SystemUIDialog.onStart(SystemUIDialog.java:109)
```

**Comment by rcstar6696** [comment]
should be resolved
